spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0
spring.web.resources.static-locations=classpath:/static/,file:uploaded-files/

server.port=8080
jwt.secret.key=dGhpc2lzbXliaWxsaW5nc29mdHdhcmVzZWNyZXRla2V5
debug=true


razorpay.key.id=rzp_test_HwqlZVsAyWZnss
razorpay.key.secret=rJ5Umro6VX5PSXwe2Ug31PZJ